### ISSUE TITLE
Could not load the "sharp" module using the darwin-arm64 runtime

### ISSUE THREAD

**Issue by NikitaVr** [elizaOS/eliza#1119]
**Describe the bug**

When following the quickstart guide, once I get to running a character I get this error

`Could not load the "sharp" module using the darwin-arm64 runtime`

after running `pnpm start --character="characters/trump.character.json"` 

**To Reproduce**

- On M2 Macbook Air
- `nvm use 23.3.0`
- `git clone https://github.com/ai16z/eliza.git`
- `cd eliza`
- `git checkout $(git describe --tags --abbrev=0)`
- `pnpm install -w --include=optional sharp`
- `pnpm build`
- `pnpm start --character="characters/trump.character.json"`

This produces the error

```
pnpm start --character="characters/trump.character.json"
 ℹ INFORMATIONS
   Loading embedding settings:
   {"USE_OPENAI_EMBEDDING":"","USE_OLLAMA_EMBEDDING":"","OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"}

 ℹ INFORMATIONS
   Loading character settings:
   {"ARGV":["/Users/nikita/.nvm/versions/node/v23.3.0/bin/node","/Users/nikita/Documents/chainpatrol/eliza/agent/src/index.ts","--isRoot","--character=characters/trump.character.json"],"CHARACTER_ARG":"--character=characters/trump.character.json","CWD":"/Users/nikita/Documents/chainpatrol/eliza/agent"}

Loaded .env file from: /Users/nikita/Documents/chainpatrol/eliza/.env
 ℹ INFORMATIONS
   Parsed settings:
   {"USE_OPENAI_EMBEDDING":"","USE_OPENAI_EMBEDDING_TYPE":"string","USE_OLLAMA_EMBEDDING":"","USE_OLLAMA_EMBEDDING_TYPE":"string","OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"}

/Users/nikita/Documents/chainpatrol/eliza/node_modules/sharp/lib/sharp.js:113
  throw new Error(help.join('\n'));
        ^

Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/nikita/Documents/chainpatrol/eliza/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (/Users/nikita/Documents/chainpatrol/eliza/node_modules/sharp/lib/constructor.js:10:1)

Node.js v23.3.0
/Users/nikita/Documents/chainpatrol/eliza/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ai16z/agent@0.1.5-alpha.5 start: `node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/trump.character.json"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Expected behavior**

- The character should run and I should be able to speak to it

**Screenshots**

**Additional context**

**Comment by wuichen** [comment]
same error happens on m1 macbook pro

**Comment by miraclemenikelechi** [comment]
+1

**Comment by 0xSmick** [comment]
+1 same error on m1

**Comment by 0xSmick** [comment]
Okay this took a really long time to solve but after 6 hours, I figured it out. 

You cannot use libvips globally, and this is said specifically in the sharp documentation: https://sharp.pixelplumbing.com/install#custom-libvips

```The use of a globally-installed libvips is unsupported on Windows and on macOS when running Node.js under Rosetta.```

So in order for this to work you need to:
1. brew uninstall libvips
2. pnpm install sharp --force -w
3. pnpm build
4. pnpm start

I also added in package.json:

 "supportedArchitectures": {
            "os": [
                "darwin",
                "current"
            ],
            "cpu": [
                "arm64"
            ]
        }

but unclear if this did anything.

**Comment by cdrn** [comment]
Thanks for this 0xSmick, it just works (tm)

**Comment by AIFlowML** [comment]
Glad you solved but I run on M4 and no issues this side.
