### ISSUE TITLE
"TypeError: response.body?.getReader is not a function" from package/plugin-node

### ISSUE THREAD

**Issue by y4my4my4m** [elizaOS/eliza#1265]
**Describe the bug**

When attempting to produce speech using elevenlabs, from my discord bot, there is an error regarding `getReader is not a function`.

https://github.com/ai16z/eliza/blob/81d027327ebba82ef3ed473d0e914c90e18e362d/packages/plugin-node/src/services/speech.ts#L126C1-L126C16

I attempted to replace the fetch call with the official elevenlabs js package but wasn't successful

**To Reproduce**

1. create discord bot character
2. add to voice chat
3. talk to it
4. text response is generated, elevenlabs processing fails, defaults to the viits audio

**Expected behavior**

1. create discord bot character
2. add to voice chat
3. talk to it
4. text response is generated, elevenlabs processing fails, properly outputs the elevenlabs audio

**Screenshots**

**Additional context**

```
node v23.3.0
linux 6.12 - manjaro
```

**Comment by y4my4my4m** [comment]
By the way, replacing the current code for elevenlabs package gives this error:

```bash
Speech generation error: ElevenLabsError: this.readableStream.getReader is not a function                                                                                                                                                               
    at TextToSpeech.<anonymous> (eliza/node_modules/elevenlabs/api/resources/textToSpeech/client/Client.js:253:27)                                                                                                              
    at Generator.next (<anonymous>)                                                                                                                                                                                                                     
    at fulfilled (eliza/node_modules/elevenlabs/api/resources/textToSpeech/client/Client.js:31:58)                                                                                                                              
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
 ```
