### ISSUE TITLE
Broken Docker image on fresh build

### ISSUE THREAD

**Issue by timolegros** [elizaOS/eliza#1460]
**Describe the bug**

Built Docker image (`pnpm docker:run`) fails to start - exits with the following error:
```
2024-12-26 07:24:12 /app/agent:
2024-12-26 07:24:12  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.1 start: `node --loader ts-node/esm src/index.ts "--isRoot"`
2024-12-26 07:24:12 Exit status 1
2024-12-26 07:24:12  WARN   Local package.json exists, but node_modules missing, did you mean to install?
2024-12-26 07:24:12 (node:31) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
2024-12-26 07:24:12 --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
2024-12-26 07:24:12 (Use `node --trace-warnings ...` to show where the warning was created)
2024-12-26 07:24:12 (node:31) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
2024-12-26 07:24:12 (Use `node --trace-deprecation ...` to show where the warning was created)
2024-12-26 07:24:12 
2024-12-26 07:24:12 node:internal/modules/run_main:122
2024-12-26 07:24:12     triggerUncaughtException(
2024-12-26 07:24:12     ^
2024-12-26 07:24:12 Error: Cannot find package '@elizaos/adapter-postgres' imported from /app/agent/src/index.ts
2024-12-26 07:24:12     at packageResolve (/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
2024-12-26 07:24:12     at moduleResolve (/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
2024-12-26 07:24:12     at Object.defaultResolve (/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
2024-12-26 07:24:12     at /app/node_modules/ts-node/src/esm.ts:218:35
2024-12-26 07:24:12     at entrypointFallback (/app/node_modules/ts-node/src/esm.ts:168:34)
2024-12-26 07:24:12     at /app/node_modules/ts-node/src/esm.ts:217:14
2024-12-26 07:24:12     at addShortCircuitFlag (/app/node_modules/ts-node/src/esm.ts:409:21)
2024-12-26 07:24:12     at resolve (/app/node_modules/ts-node/src/esm.ts:197:12)
2024-12-26 07:24:12     at nextResolve (node:internal/modules/esm/hooks:748:28)
2024-12-26 07:24:12     at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
2024-12-26 07:24:12 
2024-12-26 07:24:12 Node.js v23.3.0
2024-12-26 07:24:12  ELIFECYCLE  Command failed with exit code 1.
```

You can fix this issue by running `pnpm install --no-frozen-lockfile` before executing `pnpm docker:build` but the installed dependencies should not affect the image build process.

**To Reproduce**
Prerequisites:
- Ubuntu/Debian
- Docker installed
- PNPM installed
- Repo cloned
- `main` branch checked out

1. `pnpm clean`
2. `pnpm docker:build`
3. `pnpm docker:run`
4. `docker logs eliza`

**Expected behavior**

The container should not exit with a dependency error and should start as normal regardless of whether `pnpm install` was executed before `pnpm docker:build`.

**Screenshots**

**Additional context**

Possibly related to: https://github.com/elizaOS/eliza/pull/1120 and https://github.com/elizaOS/eliza/pull/1352

**Comment by HashWarlock** [comment]
I assume this is an amd64 cpu? I will try to reproduce and see what is wrong here.

**Comment by timolegros** [comment]
> I assume this is an amd64 cpu? I will try to reproduce and see what is wrong here.

Yes. i7-12700H - Ubuntu 22.04.5 
Also tried on Intel Xeon Platinum 8000 series - Ubuntu 24

**Comment by aijustinmoon** [comment]
I tried `pnpm install --no-frozen-lockfile` without docker and it doesn't work

**Comment by HashWarlock** [comment]
This says the adapter-postgres cannot be found. Which version of the codebase are you using so I can try to reproduce.

**Comment by michaeljoser** [comment]
getting same issue with 0.1.7-alpha.2  on x86_64 ubuntu server 24.04.1

**Comment by timolegros** [comment]
> This says the adapter-postgres cannot be found. Which version of the codebase are you using so I can try to reproduce.

Tried on release v0.1.6, v0.1.7-alpha.1 as well as latest `main`.

**Comment by vladhalla** [comment]
I have the same issue. I tried the troubleshooting from other issues like using node 18, etc but could not solve the issue yet.

**Comment by HashWarlock** [comment]
There must be something introduced that broke the build

**Comment by AIFlowML** [comment]
Interesting

**Comment by michaeljoser** [comment]
ok got it working by cleaning and rebuilding following fix from #982 

#https://github.com/elizaOS/eliza/issues/982#issuecomment-2537892452

**Comment by timolegros** [comment]
> ok got it working by cleaning and rebuilding following fix from #982
> 
> #[#982 (comment)](https://github.com/elizaOS/eliza/issues/982#issuecomment-2537892452)

This does not seem to be a fix for the same issue. This ticket relates to the Docker image i.e. `pnpm docker:build` and `pnpm docker:run`. The ticket you're referencing is unrelated to Docker. Installing dependencies and building should not be required prior to building the image.

**Comment by michaeljoser** [comment]
yes you are right, I am not using Docker and i was having the same postgres error message

**Comment by AIFlowML** [comment]
We need to investigate the cause that is also probably the platform where the docker is crearted.

**Comment by bloomberg21** [comment]
> We need to investigate the cause that is also probably the platform where the docker is crearted.

Completed how?

I have tested the docker builds and though they complete the build cycle they can not run successfully.

Are the testers using a cached docker build?

try  using
```docker system prune -a && docker compose build && docker compose up```
