### ISSUE TITLE
Installation failed on node-llama-cpp postscript

### ISSUE THREAD

**Issue by salacoste** [elizaOS/eliza#1503]
installation process stucks during quick start guide steps, installation node-llama-cpp failed and then it stuck on node_modules/@discordjs/opus: Running install script...

Used node 23.3.0

The commit version is 77b5b7d8 v0.1.7-alpha.1 

  77b5b7d8 v0.1.7-alpha.1 ● ?  pnpm install --no-frozen-lockfile                               ✔  10161  21:41:18
Scope: all 47 workspace projects
client                                   |  WARN  Installing a dependency from a non-existent directory: /Users/r2d2/Documents/Code_Projects/eliza/client/@tanstack/router-plugin/vite
packages/adapter-redis                   |  WARN  deprecated @types/ioredis@5.0.0
packages/client-discord                  |  WARN  deprecated @discordjs/voice@0.17.0
packages/client-slack                    |  WARN  deprecated @slack/events-api@3.0.1
packages/core                            |  WARN  deprecated @types/pdfjs-dist@2.10.378
packages/plugin-node                     |  WARN  deprecated @cliqz/adblocker-playwright@1.34.0
packages/plugin-story                    |  WARN  deprecated @pinata/sdk@2.1.0
packages/plugin-trustdb                  |  WARN  deprecated @types/dompurify@3.2.0
 WARN  34 deprecated subdependencies found: @cliqz/adblocker-content@1.34.0, @cliqz/adblocker-extended-selectors@1.34.0, @cliqz/adblocker@1.34.0, @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, @motionone/vue@10.16.4, @simplewebauthn/typescript-types@7.4.0, are-we-there-yet@2.0.0, are-we-there-yet@3.0.1, base-x@2.0.6, bin-version-check@6.0.0, cids@0.7.5, cids@0.8.3, core-js@2.6.12, eslint@8.57.1, ethereumjs-abi@0.6.8, gauge@3.0.2, gauge@4.0.4, glob@7.2.3, glob@8.1.0, har-validator@5.1.5, inflight@1.0.6, mkdirp@0.3.0, multiaddr@7.5.0, multibase@0.6.1, multibase@0.7.0, multibase@1.0.1, multicodec@1.0.4, npmlog@5.0.1, npmlog@6.0.2, puppeteer@19.11.1, request@2.88.2, rimraf@3.0.2, uuid@3.4.0
 WARN  Issues with peer dependencies found
client
├─┬ @vitejs/plugin-react 4.3.3
│ └── ✕ unmet peer vite@"^4.2.0 || ^5.0.0": found 0.0.0
├─┬ vite-plugin-top-level-await 1.4.4
│ └── ✕ unmet peer vite@>=2.8: found 0.0.0
└─┬ vite-plugin-wasm 3.3.0
  └── ✕ unmet peer vite@"^2 || ^3 || ^4 || ^5": found 0.0.0

packages/client-lens
└─┬ @lens-protocol/client 2.2.0
  └─┬ @lens-protocol/gated-content 0.5.1
    └─┬ @lit-protocol/node-client 2.1.62
      ├─┬ @walletconnect/ethereum-provider 2.17.3
      │ └─┬ @walletconnect/modal 2.7.0
      │   ├─┬ @walletconnect/modal-core 2.7.0
      │   │ └─┬ valtio 1.11.2
      │   │   ├── ✕ missing peer react@>=16.8
      │   │   └─┬ use-sync-external-store 1.2.0
      │   │     └── ✕ missing peer react@"^16.8.0 || ^17.0.0 || ^18.0.0"
      │   └─┬ @walletconnect/modal-ui 2.7.0
      │     └─┬ @walletconnect/modal-core 2.7.0
      │       └── ✕ missing peer react@>=16.8
      └─┬ @lit-protocol/auth-browser 2.1.62
        └─┬ @walletconnect/ethereum-provider 2.17.3
          └── ✕ missing peer react@>=16.8
Peer dependencies that should be installed:
  react@">=16.8.0 <17.0.0 || >=17.0.0 <18.0.0 || >=18.0.0 <19.0.0"

packages/core
└─┬ @langchain/core 0.3.26
  └─┬ zod-to-json-schema 3.24.1
    └── ✕ unmet peer zod@^3.24.1: found 3.23.8

packages/plugin-0g
└─┬ @0glabs/0g-ts-sdk 0.2.1
  └── ✕ unmet peer ethers@6.13.1: found 6.13.4

packages/plugin-goat
├─┬ @goat-sdk/wallet-viem 0.1.3
│ └── ✕ unmet peer @goat-sdk/core@0.3.4: found 0.3.8
└─┬ @goat-sdk/plugin-coingecko 0.1.4
  ├── ✕ unmet peer @goat-sdk/core@0.3.14: found 0.3.8
  └── ✕ unmet peer viem@2.21.49: found 2.21.53

Packages: +4705
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 4088, reused 3922, downloaded 0, added 4705, done
node_modules/@swc/core: Running postinstall script...
node_modules/canvas: Running install script...
node_modules/node-llama-cpp: Running postinstall script, failed in 1.6s
node_modules/node-llama-cpp postinstall$ node ./dist/cli/cli.js postinstall
**_└─ Failed in 1.6s at /Users/r2d2/Documents/Code_Projects/eliza/node_modules/node-llama-cpp_**
**_node_modules/@discordjs/opus: Running install script..._**

**Comment by Noveleader** [comment]
Not able to reproduce, can you also specify `pnpm` version too. 

You can check it using `pnpm --version`

**Comment by salacoste** [comment]
i was able sucessfully installed this release on old intel based mac, but struggle to make it works on Apple silicon (that's the one difference between these 2 systems, the rest like node version, pnpm and the rest were the same). 

pnpm 9.15.1 were used for both, node 23+.

I'm keen to make it work on my main mac (Apple silicon), still curious if we can solve it.

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards

**Comment by salacoste** [comment]
i have researched the question about cpp and found out the following:


```
npx --no node-llama-cpp inspect gpu

(node:46665) ExperimentalWarning: CommonJS module /Users/r2d2/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/r2d2/.nvm/versions/node/v23.3.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
OS: macOS 22.3.0 (x64)
Node: 23.3.0 (x64)
TypeScript: 5.6.3
node-llama-cpp: 3.1.1

Metal: not supported by llama.cpp on Intel Macs
[1]    46665 illegal hardware instruction  npx --no node-llama-cpp inspect GPU
```
I have M2 Chip

**Comment by bkotrys** [comment]
I have exactly the same problem

**Comment by Noveleader** [comment]
I have a M4 machine and it works perfectly on my device with pnpm version being `9.15.0` and node version being `23.3.0`. I was not able to reproduce the problem here.

**Comment by bkotrys** [comment]
The problem seems to be explicitly related to M2 machines.

**Comment by haskell-monad** [comment]
have you found a solution?

**Comment by salacoste** [comment]
![image_2025-01-01_13-45-03](https://github.com/user-attachments/assets/5e0fc7d4-8915-4a93-8bd1-447635901f51)
guys helped me to catch an initial root cause of the problem, nvm installs x64 versions of nodeJs to arm system. 
They work fine unless some certain cpp methods and calls which were caused by this mismatch.
 
 You need to check that you have the proper node version in your system otherwise 
  ```bash
 node -e "console.log(process.platform, process.arch)"                   
darwin arm64
```

I have reinstalled nodejs package natively in the system, remove nvm usage as it didn't support arm version of node. 

but later I encountered with bunch of problems the package compatibility as some of them support only x64 architecture: like esbuild, rollup, sharp...

I was able to fix them by changing dependencies in package.json(s) on arm supported versions or sometimes just updated their versions up to the most recent. 

But I'm stuck at sharp package with the following logs:

```bash

npm start      
 WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.15.1"})

> eliza@ start /Users/r2d2/Documents/Code_Projects/eliza
> pnpm --filter "@elizaos/agent" start --isRoot

.                                        |  WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.14.4"})
docs                                     |  WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.14.4"})

> @elizaos/agent@0.1.7-alpha.2 start /Users/r2d2/Documents/Code_Projects/eliza/agent
> node --loader ts-node/esm src/index.ts "--isRoot"

(node:8415) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8415) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[ElizaLogger] Initializing with:
            isNode: true
            verbose: false
            VERBOSE env: undefined
            NODE_ENV: undefined
        
 ℹ INFORMATIONS
   Loading embedding settings: 
   {"OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"} 

 ℹ INFORMATIONS
   Loading character settings: 
   {"ARGV":["/usr/local/bin/node","/Users/r2d2/Documents/Code_Projects/eliza/agent/src/index.ts","--isRoot"],"CWD":"/Users/r2d2/Documents/Code_Projects/eliza/agent"} 

 ℹ INFORMATIONS
   Parsed settings: 
   {"USE_OPENAI_EMBEDDING_TYPE":"undefined","USE_OLLAMA_EMBEDDING_TYPE":"undefined","OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"} 

using deprecated parameters for the initialization function; pass a single object instead
/Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/sharp.js:113
  throw new Error(help.join('\n'));
        ^

**_Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp_**
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1740:14)
    at Object..js (node:internal/modules/cjs/loader:1905:10)
    at Module.load (node:internal/modules/cjs/loader:1474:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at Module.require (node:internal/modules/cjs/loader:1496:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/constructor.js:10:1)

Node.js v23.5.0
/Users/r2d2/Documents/Code_Projects/eliza/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.2 start: `node --loader ts-node/esm src/index.ts "--isRoot"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

```


I tried different options and things to come over the problem but was unsuccessful so far. 

Any ideas on that though?

by the way,it worth to make the package list more compatible across different platforms. some versions were used old one which doesn't have such compatability.

**Comment by haskell-monad** [comment]
> ![image_2025-01-01_13-45-03](https://private-user-images.githubusercontent.com/12632895/399585531-5e0fc7d4-8915-4a93-8bd1-447635901f51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3ODIyNjgsIm5iZiI6MTczNTc4MTk2OCwicGF0aCI6Ii8xMjYzMjg5NS8zOTk1ODU1MzEtNWUwZmM3ZDQtODkxNS00YTkzLThiZDEtNDQ3NjM1OTAxZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDAxMzkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTMxN2ZmZTUzYTQ0ZGYxYWRmY2JmYjRlNTBjOTQ5ODkyNmM4MzQwYjFhMjFkMzdmZTFmZWM2NDUzNjQ3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qzLo5Y8PTzEnrcNPlzdIf2M9xP3iG7XCnFCG2lZZ32k) guys helped me to catch an initial root cause of the problem, nvm installs x64 versions of nodeJs to arm system. They work fine unless some certain cpp methods and calls which were caused by this mismatch.
> 
> You need to check that you have the proper node version in your system otherwise
> 
> ```shell
> node -e "console.log(process.platform, process.arch)"                   
> darwin arm64
> ```
> 
> I have reinstalled nodejs package natively in the system, remove nvm usage as it didn't support arm version of node.
> 
> but later I encountered with bunch of problems the package compatibility as some of them support only x64 architecture: like esbuild, rollup, sharp...
> 
> I was able to fix them by changing dependencies in package.json(s) on arm supported versions or sometimes just updated their versions up to the most recent.
> 
> But I'm stuck at sharp package with the following logs:
> 
> ```shell
> npm start      
>  WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.15.1"})
> 
> > eliza@ start /Users/r2d2/Documents/Code_Projects/eliza
> > pnpm --filter "@elizaos/agent" start --isRoot
> 
> .                                        |  WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.14.4"})
> docs                                     |  WARN  Unsupported engine: wanted: {"node":"23.3.0"} (current: {"node":"v23.5.0","pnpm":"9.14.4"})
> 
> > @elizaos/agent@0.1.7-alpha.2 start /Users/r2d2/Documents/Code_Projects/eliza/agent
> > node --loader ts-node/esm src/index.ts "--isRoot"
> 
> (node:8415) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
> --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:8415) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> [ElizaLogger] Initializing with:
>             isNode: true
>             verbose: false
>             VERBOSE env: undefined
>             NODE_ENV: undefined
>         
>  ℹ INFORMATIONS
>    Loading embedding settings: 
>    {"OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"} 
> 
>  ℹ INFORMATIONS
>    Loading character settings: 
>    {"ARGV":["/usr/local/bin/node","/Users/r2d2/Documents/Code_Projects/eliza/agent/src/index.ts","--isRoot"],"CWD":"/Users/r2d2/Documents/Code_Projects/eliza/agent"} 
> 
>  ℹ INFORMATIONS
>    Parsed settings: 
>    {"USE_OPENAI_EMBEDDING_TYPE":"undefined","USE_OLLAMA_EMBEDDING_TYPE":"undefined","OLLAMA_EMBEDDING_MODEL":"mxbai-embed-large"} 
> 
> using deprecated parameters for the initialization function; pass a single object instead
> /Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/sharp.js:113
>   throw new Error(help.join('\n'));
>         ^
> 
> **_Error: Could not load the "sharp" module using the darwin-arm64 runtime
> Possible solutions:
> - Ensure optional dependencies can be installed:
>     npm install --include=optional sharp
> - Ensure your package manager supports multi-platform installation:
>     See https://sharp.pixelplumbing.com/install#cross-platform
> - Add platform-specific dependencies:
>     npm install --os=darwin --cpu=arm64 sharp_**
> - Consult the installation documentation:
>     See https://sharp.pixelplumbing.com/install
>     at Object.<anonymous> (/Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/sharp.js:113:9)
>     at Module._compile (node:internal/modules/cjs/loader:1740:14)
>     at Object..js (node:internal/modules/cjs/loader:1905:10)
>     at Module.load (node:internal/modules/cjs/loader:1474:32)
>     at Function._load (node:internal/modules/cjs/loader:1286:12)
>     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
>     at Module.require (node:internal/modules/cjs/loader:1496:12)
>     at require (node:internal/modules/helpers:135:16)
>     at Object.<anonymous> (/Users/r2d2/Documents/Code_Projects/eliza/node_modules/sharp/lib/constructor.js:10:1)
> 
> Node.js v23.5.0
> /Users/r2d2/Documents/Code_Projects/eliza/agent:
>  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.2 start: `node --loader ts-node/esm src/index.ts "--isRoot"`
> Exit status 1
>  ELIFECYCLE  Command failed with exit code 1.
> ```
> 
> I tried different options and things to come over the problem but was unsuccessful so far.
> 
> Any ideas on that though?
> 
> by the way,it worth to make the package list more compatible across different platforms. some versions were used old one which doesn't have such compatability.

```shell
$ brew --prefix
/usr/local
```
My `Homebrew` installation is the `x86` version. Do I need to install it as `ARM` native `Homebrew`? Then install the `arm` version of node? Or do I just need to install the `arm` version of `node` without changing `Homebrew`?

**Comment by AIFlowML** [comment]
Hello mate. 
Are you usding latst version of ElizaOS and the dependencies ? 
Let us know to dig deeper. 

Here some tips 

#### 1. **TLDR (Executive Summary)**
- **Issue Essence:** Installation failure during `node-llama-cpp`'s `postinstall` script.
- **Root Cause:** Conditional logic in `postinstall` script fails on unsupported platforms, compounded by unmet peer dependencies and deprecated packages.
- **Solution Approach:** Modify `postinstall` script, resolve dependencies, and ensure platform compatibility.
- **Impact Assessment:** Prevents installation failures and ensures smooth setup on supported platforms.

#### 2. **Quick Resolution Path**
- **Immediate Steps:**
  1. Modify the `postinstall` script to handle unsupported platforms gracefully.
  2. Install or update unmet peer dependencies (`vite`, `react`, `zod`, `ethers`, `@goat-sdk/core`).
  3. Update or replace deprecated packages.

- **Exact File Locations and Line Numbers:**
  - **File:** `packages/plugin-node/scripts/postinstall.js`
  - **Lines:** Modify the conditional logic to include more platforms or skip installation gracefully.

- **Required Code Changes:**
  ```javascript
  import os from "os";
  const platform = os.platform();

  if (
      platform === "linux" &&
      !(os.release().includes("ubuntu") || os.release().includes("debian"))
  ) {
      console.log(
          "Skipping playwright installation on unsupported platform:",
          platform
      );
  } else {
      const { execSync } = await import("child_process");
      try {
          execSync("npx playwright install-deps && npx playwright install", {
              stdio: "inherit",
          });
      } catch (error) {
          console.error("Playwright installation failed:", error);
      }
  }
  ```

- **Validation Commands:**
  ```bash
  pnpm install --no-frozen-lockfile
  ```

- **Rollback Procedures:**
  - Revert changes to `postinstall.js`.
  - Reinstall previous versions of dependencies if issues arise.

#### 3. **Comprehensive Solution**
- **Detailed Technical Analysis:**
  - The `postinstall` script fails on unsupported platforms due to conditional logic. Unmet peer dependencies and deprecated packages further complicate the installation.

- **Step-by-Step Implementation:**
  1. **Modify `postinstall` Script:** Update the script to handle more platforms or skip installation gracefully.
  2. **Resolve Peer Dependencies:** Install or update `vite`, `react`, `zod`, `ethers`, and `@goat-sdk/core`.
  3. **Update Deprecated Packages:** Replace or update deprecated dependencies.
  4. **Verify Node.js Compatibility:** Ensure Node.js `23.3.0` is compatible or switch to a stable LTS version.

- **Dependencies and Side Effects:**
  - Ensure all dependencies are compatible with the modified script and updated packages.

- **Configuration Changes:**
  - Update `package.json` to reflect new dependency versions.

- **Environment Requirements:**
  - Supported platforms: Ubuntu, Debian, or other specified platforms.

- **Database Changes:**
  - No database changes required.

- **Service Impacts:**
  - Ensures smooth installation and setup of `node-llama-cpp` and related packages.

**Comment by deblanco** [comment]
Same problem here with a M2 Pro chip

**Comment by AIFlowML** [comment]
The new apple silicon is ARM based so very different from the intel one.
Anyway i run on both M2 and M4 the main repo with no issues is even better than on Linux.
Think is worth investigate but is not a bug of the repo. I keep it open and i wait your feedback on it.

**Comment by brittanylcrocker** [comment]
I'm also encountering this `illegal hardware instruction` issue on an M1 darwin x64 arch
I've tried running in Rosetta x86_64 arch as well

**Comment by creazy231** [comment]
Without using Rosetta the installation and build works but then it won't start because it says it needs `x86_64` and even if I turn Rosetta back on it still says it needs `x86_64` (because if the installation I guess)

**Comment by brittanylcrocker** [comment]
I'm using an M1 Mac and was able to install the dependencies and build the repo using arm64

**Steps:** 
Confirm you are running using arm
```
arch
expected output -> arm64
```
Reinstall node for arm64
```
nvm install stable
```

Confirm arm version of node is installed
```
node -e 'console.log(process.arch)’
expected output -> arm64
````

```
rm -rf node_modules
rm -rf pnpm-lock.yaml
```

I had to reinstall pnpm after reinstalling node
```
brew install pnpm
```

Then proceed to install deps and build
```
 pnpm install --no-frozen-lockfile  
```

```
pnpm build
```

I also followed the steps here - https://node-llama-cpp.withcat.ai/guide/Metal

Hope this helps someone!

**Comment by mohs1n** [comment]
I had the same issue with my M1 Pro which was always getting stuck on llama installation failed. 
Steps to fix it - 

* Check your arch ( probably you are on rosetta ) 
Go to your terminal and type  

` arch ` 

If it returns I386 it means it's on rosetta and installation might be giving issues because of that. 

Change your architecture to arm by using this command 

` alias arm="$env /usr/bin/arch -arm64 /bin/zsh ---login" `

if you type ` arch ` again it should give your arm64 now instead of i386 

Now, next step is to install NVM for it - 

` nvm install stable `

then 

` nvm use stable ` 

then make sure you are using correct nvm by using this command 

` node -e 'console.log(process.arch)' ` 

it should return arm64 so it means you are on correct nvm now. 

now you can go to the codebase and use 
` rm -rf node_modules              
rm -rf pnpm-lock.yaml `

And then install packages by using ` pnpm install --no-frozen-lockfile  ` 

Make sure you have xcode command line tools installed as a perquisite.

**Comment by deblanco** [comment]
This problem seems to be gone for me, maybe they updated the dep.
Now I'm stuck in this new one when I run `pnpm build` 😓 

```
CLI Target: node18
@elizaos/core:build: CLI Cleaning output folder
@elizaos/core:build: ESM Build start
@elizaos/core:build: ✘ [ERROR] Could not resolve "@huggingface/transformers"
@elizaos/core:build: 
@elizaos/core:build:     src/generation.ts:17:30:
@elizaos/core:build:       17 │ import { AutoTokenizer } from "@huggingface/transformers";
@elizaos/core:build:          ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@elizaos/core:build: 
@elizaos/core:build:   The Yarn Plug'n'Play manifest forbids importing "@huggingface/transformers" here because it's not
@elizaos/core:build:   listed as a dependency of this package:
@elizaos/core:build: 
@elizaos/core:build:     ../../../../.pnp.cjs:48:31:
@elizaos/core:build:       48 │         "packageDependencies": [\
@elizaos/core:build:          ╵                                ~~
@elizaos/core:build: 
@elizaos/core:build:   You can mark the path "@huggingface/transformers" as external to exclude it from the bundle, which
@elizaos/core:build:   will remove this error and leave the unresolved path in the bundle.
@elizaos/core:build: 
@elizaos/core:build: ESM Build failed
@elizaos/core:build: Error: Build failed with 1 error:
@elizaos/core:build: src/generation.ts:17:30: ERROR: Could not resolve "@huggingface/transformers"
```

<img width="587" alt="image" src="https://github.com/user-attachments/assets/46e3457a-5f02-4f21-88a5-d499ccef4e06" />

Help please

**Comment by haskell-monad** [comment]
I completely uninstalled my `M1 homebrew` (based on `x86`), reinstalled an `arm` version of `homebrew`, then reinstalled the `arm` version of `node`, and then configured `iTerm2` to use `arm` startup (install the latest version of `iTerm2`, which is `arm` by default), Then I can successfully build `eliza`

**Comment by AIFlowML** [comment]
I did nothing like that and i installed on all macs. 
I think all have serioues permission problems.

**Comment by michaelgreen06** [comment]
> This problem seems to be gone for me, maybe they updated the dep. Now I'm stuck in this new one when I run `pnpm build` 😓
> 
> ```
> CLI Target: node18
> @elizaos/core:build: CLI Cleaning output folder
> @elizaos/core:build: ESM Build start
> @elizaos/core:build: ✘ [ERROR] Could not resolve "@huggingface/transformers"
> @elizaos/core:build: 
> @elizaos/core:build:     src/generation.ts:17:30:
> @elizaos/core:build:       17 │ import { AutoTokenizer } from "@huggingface/transformers";
> @elizaos/core:build:          ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> @elizaos/core:build: 
> @elizaos/core:build:   The Yarn Plug'n'Play manifest forbids importing "@huggingface/transformers" here because it's not
> @elizaos/core:build:   listed as a dependency of this package:
> @elizaos/core:build: 
> @elizaos/core:build:     ../../../../.pnp.cjs:48:31:
> @elizaos/core:build:       48 │         "packageDependencies": [\
> @elizaos/core:build:          ╵                                ~~
> @elizaos/core:build: 
> @elizaos/core:build:   You can mark the path "@huggingface/transformers" as external to exclude it from the bundle, which
> @elizaos/core:build:   will remove this error and leave the unresolved path in the bundle.
> @elizaos/core:build: 
> @elizaos/core:build: ESM Build failed
> @elizaos/core:build: Error: Build failed with 1 error:
> @elizaos/core:build: src/generation.ts:17:30: ERROR: Could not resolve "@huggingface/transformers"
> ```
> 
> <img alt="image" width="587" src="https://private-user-images.githubusercontent.com/343824/402178118-46e3457a-5f02-4f21-88a5-d499ccef4e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTQ1NzUsIm5iZiI6MTczNjc1NDI3NSwicGF0aCI6Ii8zNDM4MjQvNDAyMTc4MTE4LTQ2ZTM0NTdhLTVmMDItNGYyMS04OGE1LWQ0OTljY2VmNGUwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QwNzQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDhmNzAwZmQyZjA3ZTJjMGIzMmI1ZjRhNmI4YTlkMDY0OTIwZDUwYTI5MmNhNzAzOWI1ZDZiMzg0MjZmMWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HWmGPxkDenoQaK7MI0Mg7Xe2kkzszOVZS_vl3xcURRM">
> Help please

I have the exact same error when trying to run `pnpm build` on the latest branch. At time of writing I'm on v0.1.8+build.1

**Comment by deblanco** [comment]
Hey, 3 days later, I ended up fixing it.
I removed from my user root folder the file `.pnp.cjs`, it seems that it does some conflict with "yarn berry"

```
rm -rf ~/.pnpn.cjs
```

after it, on the Eliza folder:

```
rm -rf node_modules/ && pnpm install --no-frozen-lockfile && pnpm build
```

and voilá, it compiled, and I was able to start the project

Happy coding!

**Comment by jbelelieu** [comment]
So I had the same issue:

```
node_modules/node-llama-cpp postinstall$ node ./dist/cli/cli.js postinstall
└─ Failed in 1.6s at /Applications/consensys/pickle_music/bella_ai_bot/node_modules/node-llama-cpp
```

```
OS: macOS 24.1.0 (x64)
Node: 23.6.0 (x64)
TypeScript: 5.7.3
node-llama-cpp: 3.1.1

Metal: not supported by llama.cpp on Intel Macs

CPU model: Apple M2 Max
```

But I was able to fix the issue by following the directions in this comment: https://github.com/elizaOS/eliza/issues/1503#issuecomment-2575003206

In particular, for me, the issue was that the arm version of node wasn't running.

Everything's peaches now, so thanks @brittanylcrocker!

**Comment by veebull** [comment]
> rm -rf ~/.pnpn.cjs

@deblanco there is no `~/.pnpn.cjs` file in error, maybe `~/.pnp.cjs` ?


correct commands
```bash
rm -rf ~/.pnp.cjs
```
then
```bash
rm -rf node_modules/ && pnpm install --no-frozen-lockfile && pnpm build
```

**Comment by deblanco** [comment]
> > rm -rf ~/.pnpn.cjs
> 
> [@deblanco](https://github.com/deblanco) there is no `~/.pnpn.cjs` file in error, maybe `~/.pnp.cjs` ?
> 
> correct commands
> 
> rm -rf ~/.pnp.cjs
> then
> 
> rm -rf node_modules/ && pnpm install --no-frozen-lockfile && pnpm build

yes, you are right!
