### ISSUE TITLE
Unable to load sqlite-vec extensions in docker environment

### ISSUE THREAD

**Issue by iankm** [elizaOS/eliza#1543]
**Describe the bug**

Upon building the docker container and running locally, I am unable to start my agent. The agent works when I build in my local terminal.

When I run the docker container, I receive the issue in the provided screenshot.

I mainly interact with my agent via the Discord client. When I run locally, it responds to my messages and I can see the logs in terminal. When I run via docker, this does not occur.

**To Reproduce**

1. Run `docker build -t latest .`
2. Run `docker run latest`

**Expected behavior**

I should be able to interact with my agent via Discord and see the appropriate logs in my terminal.

**Screenshots**

<img width="937" alt="CleanShot 2024-12-28 at 14 38 51@2x" src="https://github.com/user-attachments/assets/2779a416-5969-4b76-a9d7-c68ece191f01" />

**Additional context**

**Comment by IntrinsiCrypto** [comment]
Can reproduce the issue, seems this is because the package doesn't have a `linux-arm64` target: https://github.com/asg017/sqlite-vec/issues/148

**Comment by HashWarlock** [comment]
Can you try running:
docker buildx build --platform=linux/amd64 -t eliza:latest . Then try to run the container?

Maybe we can add a system architecture check during the docker build script

**Comment by iankm** [comment]
Will do

**Comment by iankm** [comment]
This worked! Thank you

**Comment by AIFlowML** [comment]
This issue should be closed.

**Comment by Lomank123** [comment]
Greetings, stumbled upon the same issue. Tried to run `docker buildx build --platform=linux/amd64 -t eliza:latest .` as @HashWarlock suggested but now it returns this error during the build stage:

```
199.4 node_modules/@discordjs/opus install: gyp ERR! build error 
199.4 node_modules/@discordjs/opus install: gyp ERR! stack Error: `make` failed with exit code: 2
199.4 node_modules/@discordjs/opus install: gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/build.js:209:23)
199.4 node_modules/@discordjs/opus install: gyp ERR! System Linux 6.10.14-linuxkit
199.4 node_modules/@discordjs/opus install: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36/opus.node" "--module_name=opus" "--module_path=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
199.4 node_modules/@discordjs/opus install: gyp ERR! cwd /app/node_modules/@discordjs/opus
199.4 node_modules/@discordjs/opus install: gyp ERR! node -v v23.3.0
199.4 node_modules/@discordjs/opus install: gyp ERR! node-gyp -v v10.1.0
199.4 node_modules/@discordjs/opus install: gyp ERR! not ok 
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! build error 
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36/opus.node --module_name=opus --module_path=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! System Linux 6.10.14-linuxkit
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/@discordjs/opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! cwd /app/node_modules/@discordjs/opus
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! node -v v23.3.0
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! node-pre-gyp -v v0.4.5
199.4 node_modules/@discordjs/opus install: node-pre-gyp ERR! not ok 
199.4 node_modules/@discordjs/opus install: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36/opus.node --module_name=opus --module_path=/app/node_modules/@discordjs/opus/prebuild/node-v131-napi-v3-linux-x64-glibc-2.36 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
199.5 node_modules/@discordjs/opus install: Failed
199.5  ELIFECYCLE  Command failed with exit code 1.
```

Does anyone faced the same? I would appreciate any help on that.

**Comment by HashWarlock** [comment]
Are you running DockerHub or Orbstack? Orbstack is better for building docker for platform= linux/amd64

**Comment by Lomank123** [comment]
DockerHub. I've resolved the issue by following zxflows' answer in "ElizaOS Development" Discord channel. To fix it, in Docker Desktop general settings I've changed Virtual Machine option to "Docker VMM" instead of "Apple Virtualization Framework" and built the image. Many thanks

Discord message link: https://discord.com/channels/1051457140637827122/1323727516745334785/1325014844075937792

**Comment by AIFlowML** [comment]
Closing this issue because not related to the general avaiable code. 
Anyway @HashWarlock It will be good practice to add this information to the docs. 
https://discord.com/channels/1051457140637827122/1323727516745334785/1325014844075937792

**Comment by tweedyant** [comment]
hi! i am getting the same error, running on Mac M1. Rebuilt by using suggested command, docker buildx build --platform=linux/amd64 -t eliza:latest . , but am still getting the same error message and behavior, as seen in the attached image.

<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/4220824f-e6b3-4947-bc82-9f889611de96" />

**Comment by HashWarlock** [comment]
> hi! i am getting the same error, running on Mac M1. Rebuilt by using command by @HashWarlock , docker buildx build --platform=linux/amd64 -t eliza:latest . , but am still getting the same error message and behavior, as seen in the attached image.
> 
> edit: also tried rebuilding with slightly different command, docker buildx build --platform=linux/arm64 -t eliza:latest . , which also yields the same error. 
> 
> any insight would be much appreciated! 
> 
> <img width="1131" alt="Image" src="https://github.com/user-attachments/assets/4220824f-e6b3-4947-bc82-9f889611de96" />

Did you change your settings in docker? I also saw something the other day in the case you recently upgraded Mac OS https://em.docker.com/NzkwLVNTQi0zNzUAAAGYME8SNiHnwuJ2PfWQAUBtirDPLaWQYpkcovl0Jy0chWco1eR6PbxB8tS0K8OpldHnD2IZymw=
![Screenshot_20250124_095252_Proton Mail.png](https://github.com/user-attachments/assets/b3970f8e-a8b8-46e4-9624-5bbd191a2b3e)

**Comment by tweedyant** [comment]
@HashWarlock thanks for the insight, from what I can tell, I'm using the newest version of docker. not quite sure the reason for the behavior i'm experiencing. 

<img width="646" alt="Image" src="https://github.com/user-attachments/assets/5201752a-a6d5-4e2a-9fa0-fb5e748f47b1" />
