### ISSUE TITLE
Telegram connection

### ISSUE THREAD

**Issue by ALGOREX-PH** [elizaOS/eliza#1562]
How can I fix this?

I just added my telegram bot token and character.ts clients to Add telegram.

However when I pnpm start I get this error :

“ SUCCESS
   SUCCESS 
   Creating runtime for character 
   Hikari 

 âœ“ SUCCESS
   Agent ID 
   1004db53-bf1b-0d1a-ba4c-01d318a8197d 

 ["âœ“ Registering action: CONTINUE"] 

 ["âœ“ Registering action: FOLLOW_ROOM"] 

 ["âœ“ Registering action: UNFOLLOW_ROOM"] 

 ["âœ“ Registering action: IGNORE"] 

 ["âœ“ Registering action: NONE"] 

 ["âœ“ Registering action: MUTE_ROOM"] 

 ["âœ“ Registering action: UNMUTE_ROOM"] 

 â—Ž LOGS
   Registering service: 
   browser 

 â—Ž LOGS
   Registering service: 
   image_description 

 â—Ž LOGS
   Registering service: 
   text_generation 

 â—Ž LOGS
   Registering service: 
   pdf 

 â—Ž LOGS
   Registering service: 
   speech_generation 

 â—Ž LOGS
   Registering service: 
   transcription 

 â—Ž LOGS
   Registering service: 
   video 

 ["âœ“ Server running at http://localhost:3000/"] 

 ["âœ“ Service browser initialized successfully"] 

 ["âœ“ Service image_description initialized successfully"] 

 ["âœ“ Service text_generation initialized successfully"] 

 ["âœ“ Service pdf initialized successfully"] 

 ["âœ“ Service speech_generation initialized successfully"] 

 ["âœ“ Service transcription initialized successfully"] 

 ["âœ“ Service video initialized successfully"] 

 ["â—Ž ðŸ“± Constructing new TelegramClient..."] 

 ["â—Ž âœ… TelegramClient constructor completed"] 

 ["â—Ž ðŸš€ Starting Telegram bot..."] 

 ["â—Ž âœ¨ Telegram bot successfully launched and is running!"] 

 â›” ERRORS
   âŒ Failed to launch Telegram bot: 
   {"message":"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: ","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"} 

 â›” ERRORS
   Error starting agent for character Hikari: 
   {"message":"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: ","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"} 

FetchError: request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:512:5)
    at TLSSocket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
    at runNextTicks (node:internal/process/task_queues:69:3)
    at listOnTimeout (node:internal/timers:555:9) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
 â›” ERRORS
   Error starting agents: 
   {"message":"request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: ","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"} 

 ["â—Ž Chat started. Type 'exit' to quit."] 

You: 
/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://api.telegram.org/bot7813398684:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/algorex/eliza-starter/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:512:5)
    at TLSSocket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v22.12.0
â€‰ELIFECYCLEâ€‰ Command failed with exit code 1.

**Comment by AIFlowML** [comment]
**Based on the code from the telegramClient.ts file, the issue you're experiencing seems to be related to a timeout error when the Telegram bot tries to connect to the Telegram API. Here are some steps you can take to troubleshoot and potentially resolve this issue:**

Check Network Connectivity: Ensure that your server or local machine has a stable internet connection. The ETIMEDOUT error indicates that the request to the Telegram API is timing out, which could be due to network issues.

 Verify Telegram Bot Token: Double-check that the bot token you are using is correct. An incorrect token could lead to failed API requests.

 API Endpoint Accessibility: Make sure that the Telegram API endpoint (https://api.telegram.org) is accessible from your network. You can test this by trying to access the endpoint using a tool like curl or a web browser.

Firewall and Security Groups: If you're running this on a cloud server, ensure that your firewall or security groups are not blocking outbound requests to the Telegram API.

Proxy Settings: If your network requires a proxy to access the internet, ensure that your application is configured to use it.

**Comment by jiaohu** [comment]
> **Based on the code from the telegramClient.ts file, the issue you're experiencing seems to be related to a timeout error when the Telegram bot tries to connect to the Telegram API. Here are some steps you can take to troubleshoot and potentially resolve this issue:**
> 
> Check Network Connectivity: Ensure that your server or local machine has a stable internet connection. The ETIMEDOUT error indicates that the request to the Telegram API is timing out, which could be due to network issues.
> 
> Verify Telegram Bot Token: Double-check that the bot token you are using is correct. An incorrect token could lead to failed API requests.
> 
> API Endpoint Accessibility: Make sure that the Telegram API endpoint (https://api.telegram.org) is accessible from your network. You can test this by trying to access the endpoint using a tool like curl or a web browser.
> 
> Firewall and Security Groups: If you're running this on a cloud server, ensure that your firewall or security groups are not blocking outbound requests to the Telegram API.
> 
> Proxy Settings: If your network requires a proxy to access the internet, ensure that your application is configured to use it.

I have added proxy in https://github.com/elizaOS/eliza/blob/30670640d0670f203f73b914a81e241d8079b838/packages/client-telegram/src/telegramClient.ts#L18 like this
```ts
        this.bot = new Telegraf(botToken, {
            telegram: {
              agent: new HttpsProxyAgent("http://127.0.0.1:7890"),
            },
          });
```
but it does not work well, and I am sure this method works well, for I have do the same thing in my own telegram project

**Comment by harjotjuneja6** [comment]
Hi , is this issue fixed or it needs to be fixed ?

**Comment by jiaohu** [comment]
> Hi , is this issue fixed or it needs to be fixed ?

do not fixed yet

**Comment by AIFlowML** [comment]
Can you remove the proxy and try a run ? Can you add logging on that proxy to see if the error is originated by the client or by the proxy ? Some proxies are banned or IP sensitive.

**Comment by alwaysabetterway** [comment]
well how about making sure that you can connect from the server first, try: 

```
curl -X GET "https://api.telegram.org/$BOTIDGOESHERE:$YOURBOTTOKENGOESHERE/getMe"

```

If you get a response with the information from your bot, then it seems to connect ok. I'm having the same error me
ssage but I think this is something else, maybe it just times out too quickly. I'll try to debug it.

**Comment by alwaysabetterway** [comment]
> Can you remove the proxy and try a run ? Can you add logging on that proxy to see if the error is originated by the client or by the proxy ? Some proxies are banned or IP sensitive.

w/o the proxy it fails as shown above ETIMEOUT, 

I added more logs:

```
        this.bot = new Telegraf(botToken, {
            telegram: {
              agent: new HttpsProxyAgent("http://127.0.0.1:7890").on('error', (err) => {
                console.error('Proxy Error:', err);
              }).on('connect', (response, socket, head) => {
                console.log('Proxy Connected:', response.statusCode);
              })
            },
           });
```


but it just hands at

```
 ["ℹ Initializing LlamaService..."]

Initializing AwsS3Service
 ◎ LOGS
   initializeClients
   ["twitter","telegram"]
   for
   xxxxx

 ["◎ 📱 Constructing new TelegramClient..."]

 ["◎ ✅ TelegramClient constructor completed"]

 ["◎ 🚀 Starting Telegram bot..."]

```

**Comment by AIFlowML** [comment]
If telegram fail with no proxy maybe you cannot reach the telegram endpoint at all. 
To futher investigate consider to run a fresh build from scratch with jusr the telegram client on a new character.
If you cannot absolutely connect then is an IP issuebut i would like to have your feedback on this.

**Comment by lagrossi** [comment]
I found that the request is defaulting to IPv6 which i'm not running on my network and therefore is failing. So I instead updated the options within telegramClient.ts to include option to force IPv4 and increase the timeout to 5 seconds. 

I added in the telegram options , family and timeout. That seem to do the trick. 


        this.options = {
            telegram: {
                apiRoot: runtime.getSetting("TELEGRAM_API_ROOT") || process.env.TELEGRAM_API_ROOT || "https://api.telegram.org",
                family: 4,
                timeout: 5000
            },
        };
