### ISSUE TITLE
Windows 11:  Command Failed with exit Code 7:

### ISSUE THREAD

**Issue by notOccupanther** [elizaOS/eliza#461]
During **pnpm i** section of the  install I received the following error " _ELIFECYCLE  Command failed with exit code 7._"

I managed to fix it, by manually downlaoding the Discord Opus piece that it failed on, but for some reason, it is not downloading via the script.

I tried downloading to the actual directory via a browser and it failed - windows reported the download reported an error,.  So I downloaded it into the 'downloads' folder under my profile and manually copied the file in.  I then extracted the files and re-ran 

pnpm i 

It seems to have worked.  So this is an FYI really.  

Thanks

N

C:\Users\clancynl\Documents\GitHub\eliza-starter>pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +1108
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1108, reused 1108, downloaded 0, added 0, done
node_modules/.pnpm/es5-ext@0.10.64/node_modules/es5-ext: Running postinstall script, done in 167ms
node_modules/.pnpm/@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02/node_modules/@discordjs/opus: Running install script, failed in 640ms
.../node_modules/@discordjs/opus install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.4.5
│ node-pre-gyp info using node@23.2.0 | win32 | x64
│ (node:30168) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus\prebuild\node-v131-napi-v3-win32-x64-unknown-unknown\opus.node" (not found)
│ node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.9.0 and node@23.2.0 (node-v131 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp ERR! UNCAUGHT EXCEPTION
│ node-pre-gyp ERR! stack Error: spawn EINVAL
│ node-pre-gyp ERR! stack     at ChildProcess.spawn (node:internal/child_process:421:11)
│ node-pre-gyp ERR! stack     at Object.spawn (node:child_process:753:9)
│ node-pre-gyp ERR! stack     at module.exports.run_gyp (C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:72:17)
│ node-pre-gyp ERR! stack     at build (C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\build.js:36:11)
│ node-pre-gyp ERR! stack     at self.commands.<computed> [as build] (C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\node-pre-gyp.js:72:34)
│ node-pre-gyp ERR! stack     at run (C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\main.js:90:29)
│ node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
│ node-pre-gyp ERR! System Windows_NT 10.0.26120
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\clancynl\\Documents\\GitHub\\eliza-starter\\node_modules\\.pnpm\\@discordjs+node-pre-gyp@0.4.5\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
│ node-pre-gyp ERR! cwd C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus
│ node-pre-gyp ERR! node -v v23.2.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.4.5
└─ Failed in 640ms at C:\Users\clancynl\Documents\GitHub\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script, failed in 626ms (skipped as optional)
node_modules/.pnpm/puppeteer@19.11.1_bufferutil@4.0.8_typescript@5.6.3_utf-8-validate@5.0.10/node_modules/puppeteer: Running postinstall script...
node_modules/.pnpm/node-llama-cpp@3.1.1_typescript@5.6.3/node_modules/node-llama-cpp: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 7.

**Comment by sirkitree** [comment]
please try the following:
main branch, node v23.1.0, bash
pnpm clean
pnpm install
pnpm build
pnpm start --character=(file)

**Comment by lakshya404stc** [comment]
run this 
npm install -g node-pre-gyp 
then 
pnpm install @discordjs/opus

**Comment by lakshya404stc** [comment]
run this
npm install -g node-pre-gyp
then
npm install @discordjs/opus

edit **
I found a better solution

linux
before running "pnpm i"
sudo apt update && sudo apt install build-essentials && python3

windows
before running "pnpm i"
npm install --global --production windows-build-tools

**Comment by decentralized02** [comment]
I have the same error. I tried everything listed above, but to no avail.

Here is the stack trace

Lockfile is up to date, resolution step is skipped
Packages: +1108

Progress: resolved 1108, reused 1108, downloaded 0, added 3, done
node_modules/.pnpm/ffmpeg-static@5.2.0/node_modules/ffmpeg-static: Running install script, done in 67ms
node_modules/.pnpm/es5-ext@0.10.64/node_modules/es5-ext: Running postinstall script, done in 56ms
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script, failed in 934ms (skipped as optional)
node_modules/.pnpm/puppeteer@19.11.1_bufferutil@4.0.8_typescript@5.6.3_utf-8-validate@5.0.10/node_modules/puppeteer: Running postinstall script...
node_modules/.pnpm/node-llama-cpp@3.1.1_typescript@5.6.3/node_modules/node-llama-cpp: Running postinstall script, done in 562ms
node_modules/.pnpm/@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02/node_modules/@discordjs/opus: Running install script, failed in 870ms
.../node_modules/@discordjs/opus install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.4.5
│ node-pre-gyp info using node@23.3.0 | win32 | x64
│ (node:26068) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus\prebuild\node-v131-napi-v3-win32-x64-unknown-unknown\opus.node" (not found)
│ node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.9.0 and node@23.3.0 (node-v131 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.gz
│ node-pre-gyp ERR! UNCAUGHT EXCEPTION
│ node-pre-gyp ERR! stack Error: spawn EINVAL
│ node-pre-gyp ERR! stack     at ChildProcess.spawn (node:internal/child_process:421:11)
│ node-pre-gyp ERR! stack     at Object.spawn (node:child_process:753:9)
│ node-pre-gyp ERR! stack     at module.exports.run_gyp (C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:72:17)
│ node-pre-gyp ERR! stack     at build (C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\build.js:36:11)
│ node-pre-gyp ERR! stack     at self.commands.<computed> [as build] (C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\node-pre-gyp.js:72:34)
│ node-pre-gyp ERR! stack     at run (C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+node-pre-gyp@0.4.5\node_modules\@discordjs\node-pre-gyp\lib\main.js:90:29)
│ node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
│ node-pre-gyp ERR! System Windows_NT 10.0.22631
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tesse\\OneDrive\\Bureau\\eliza-starter\\node_modules\\.pnpm\\@discordjs+node-pre-gyp@0.4.5\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
│ node-pre-gyp ERR! cwd C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus
│ node-pre-gyp ERR! node -v v23.3.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.4.5
└─ Failed in 870ms at C:\Users\tesse\OneDrive\Bureau\eliza-starter\node_modules\.pnpm\@discordjs+opus@https+++codeload.github.com+discordjs+opus+tar.gz+31da49d8d2cc6c5a2ab1bfd332033ff7d5f9fb02\node_modules\@discordjs\opus
 ELIFECYCLE  Command failed with exit code 7.

**Comment by navingate** [comment]
I'm facing this issue. Any resolutions in the last two weeks?

**Comment by brayden-yates** [comment]
This is a little unusual--have you tried downgrading node.js to v17.9.1? The latest Opus release is for node module version v102, and you're on the latest version of node (module version v131.

**Comment by AIFlowML** [comment]
Hello everyone.
Did you try upgrade to the latest release of ElizaOS ? 
Can you try after the upgrade to post here ventually the errors ?

The main issue is that somehow you not downloading the file Discord Opus 
To resolve this, check compatibility with Node.js, manually download the binary, update dependencies, ensure build tools are available for source compilation, and report the issue if necessary.
Let us know.

**Comment by AIFlowML** [comment]
Close for inactivity.
