### ISSUE TITLE
Failed to initialize ONNX Runtime API

### ISSUE THREAD

**Issue by minichris** [elizaOS/eliza#881]
**Describe the bug**

When launching with `pnpm --dir core start "--character=characters/trump.character.json"` I get 
```
(node:16908) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16908) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
The requested API version [20] is not available, only API versions [1, 19] are supported in this build. Current ORT Version is: 1.19.2
node:internal/modules/cjs/loader:1724
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Failed to initialize ONNX Runtime API. It could happen when this nodejs binding was built with a higher version ONNX Runtime but now runs with a lower version ONNX Runtime DLL(or shared library).
    at Object..node (node:internal/modules/cjs/loader:1724:18)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (J:\Eliza\eliza\core\node_modules\onnxruntime-node\dist\binding.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
```

**To Reproduce**

Install following the quickstart guide on Windows 10 Education Edition, using node 23.3.0

**Expected behavior**

I don't get this error.

**Comment by EvanTedesco** [comment]
I am having a similar error on Mac OS.  It seems to be building for OS X 13.3 but I am on 11.7.10 (Big Sur).  

```
node:internal/modules/cjs/loader:1931
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/ET/eliza-agents/eliza/node_modules/onnxruntime-node/bin/napi-v3/darwin/x64/onnxruntime_binding.node, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/ET/eliza-agents/eliza/node_modules/onnxruntime-node/bin/napi-v3/darwin/x64/libonnxruntime.1.20.1.dylib (which was built for Mac OS X 13.3)
  Expected in: /usr/lib/libc++.1.dylib

    at Object..node (node:internal/modules/cjs/loader:1931:18)
    at Module.load (node:internal/modules/cjs/loader:1474:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at Module.require (node:internal/modules/cjs/loader:1496:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/ET/eliza-agents/eliza/node_modules/onnxruntime-node/dist/binding.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1740:14)
    at Object..js (node:internal/modules/cjs/loader:1905:10) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by AIFlowML** [comment]
Can you try with the latest version  and report back the errors in case? 

### Comprehensive Solution

#### 1. TLDR (Executive Summary)
- **Issue essence**: ONNX Runtime API initialization error due to version mismatch.
- **Root cause**: Mismatch between ONNX Runtime versions used in build and runtime environments.
- **Solution approach**: Align ONNX Runtime versions and update configurations.
- **Impact assessment**: Critical issue preventing application initialization.

#### 2. Quick Resolution Path
- **Immediate steps**:
  1. Verify ONNX Runtime version in both build and runtime environments.
  2. Ensure both environments use the same version (e.g., 1.19.2).
  3. Update the `package.json` to specify the correct ONNX Runtime version.
  4. Rebuild the project to ensure compatibility.

- **Exact file locations and line numbers**:
  - `package.json`: Update the ONNX Runtime dependency.
  - `agent/src/index.ts`: Review initialization code for version-specific configurations.

- **Required code changes**:
  ```json
  // package.json
  "dependencies": {
    "onnxruntime-node": "1.19.2"
  }
  ```

- **Validation commands**:
  ```bash
  npm install
  npm run build
  npm start
  ```

- **Rollback procedures**:
  Revert the `package.json` changes and reinstall the previous ONNX Runtime version.

#### 3. Comprehensive Solution
- **Detailed technical analysis**:
  The error occurs because the ONNX Runtime bindings were built with a higher version (e.g., 20) than the runtime environment supports (1.19.2). This mismatch prevents the API from initializing correctly.

- **Step-by-step implementation**:
  1. **Check ONNX Runtime version**:
     ```bash
     npm list onnxruntime-node
     ```
  2. **Update `package.json`**:
     ```json
     "dependencies": {
       "onnxruntime-node": "1.19.2"
     }
     ```
  3. **Reinstall dependencies**:
     ```bash
     npm install
     ```
  4. **Rebuild the project**:
     ```bash
     npm run build
     ```
  5. **Run the application**:
     ```bash
     npm start
     ```

**Comment by AIFlowML** [comment]
Did you try the new main build and can you give me a feedback please.
If not since i also run on OSX with no problem i think it something we already have fixed in the configuration. 
I wait feebback.

**Comment by AIFlowML** [comment]
Close for missing feedback.

**Comment by ericzon** [comment]
Hi @AIFlowML  I've just tried to downgrade to "onnxruntime-node": "1.19.2" as you said and that worked but it should be interesting to upgrade dependencies to use latest versions. Thanks!
