### ISSUE TITLE
PUPPETEER cannot be installed properly

### ISSUE THREAD

**Issue by QingyangKong** [elizaOS/eliza#992]
**Describe the bug**

the dependency cannot be installed properly when I run command `pnpm install`. I got the issue below: 
```
│ ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
│ Error: Download failed: server returned code 503. URL: https://storage.googleapis.com/chromium-browser-snapshots/Mac/1108766/chrome-mac.zip
│     at /Users/qingyangkong/environment/ai-agent/eliza/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:121:31
│     at ClientRequest.requestCallback (/Users/frank/environment/ai-agent/eliza/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:98:13)
│     at Object.onceWrapper (node:events:628:26)
│     at ClientRequest.emit (node:events:513:28)
│     at HTTPParser.parserOnIncomingClient (node:_http_client:710:27)
│     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
│     at Socket.socketOnData (node:_http_client:552:22)
│     at Socket.emit (node:events:513:28)
│     at addChunk (node:internal/streams/readable:559:12)
│     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
└─ Failed in 1m 22.5s at /Users/frank/environment/ai-agent/eliza/node_modules/puppeteer
```

**To Reproduce**
run commands:
```
git clone https://github.com/ai16z/eliza.git
pnpm install
```
**Expected behavior**

all dependencies install successfully.

**Screenshots**

**Additional context**

**Comment by HappySean2845** [comment]
use `PUPPETEER_SKIP_DOWNLOAD=true pnpm install`

**Comment by cxp-13** [comment]
> use `PUPPETEER_SKIP_DOWNLOAD=true pnpm install`
```
cxp@R9000P:~/solana_learn/AI/eliza$ pnpm install PUPPETEER_SKIP_DOWNLOAD=true -w
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  PUPPETEER_SKIP_DOWNLOAD=true isn't supported by any available resolver.
 ```
 Still not work

**Comment by AIFlowML** [comment]
Hello everyone is this isue still happening on the latest version of ElizaOS ? 

Here some tips but please let us know 

### Comprehensive Solution for Puppeteer Installation Issue

#### 1. **TLDR (Executive Summary)**
   - **Issue Essence**: Puppeteer installation fails due to a server-side issue (HTTP 503) when downloading Chromium.
   - **Root Cause**: Temporary unavailability of the Chromium storage server.
   - **Solution Approach**: Skip Chromium download, check server status, and consider manual installation.
   - **Impact Assessment**: Affects Puppeteer installation but can be mitigated with alternative approaches.

#### 2. **Quick Resolution Path**
   - **Immediate Steps**:
     1. Set the environment variable to skip Chromium download:
        ```bash
        export PUPPETEER_SKIP_DOWNLOAD=true
        ```
     2. Retry the installation:
        ```bash
        pnpm install
        ```
   - **Validation Commands**:
     - Verify Puppeteer installation:
       ```bash
        pnpm list puppeteer
        ```
   - **Rollback Procedures**:
     - Unset the environment variable if needed:
       ```bash
        unset PUPPETEER_SKIP_DOWNLOAD
        ```

#### 3. **Comprehensive Solution**
   - **Detailed Technical Analysis**:
     - The issue stems from a server-side problem with the Chromium download URL. The HTTP 503 error indicates temporary unavailability.
   - **Step-by-Step Implementation**:
     1. **Skip Chromium Download**:
        - Set `PUPPETEER_SKIP_DOWNLOAD` to `true`.
     2. **Check Server Status**:
        - Use `curl` to verify server accessibility:
          ```bash
          curl -I https://storage.googleapis.com/chromium-browser-snapshots/Mac/1108766/chrome-mac.zip
          ```
     3. **Manual Chromium Installation**:
        - Download Chromium manually and configure Puppeteer to use it:
          ```bash
          export PUPPETEER_EXECUTABLE_PATH=/path/to/chromium
          ```
     4. **Update Puppeteer Version**:
        - Modify `package.json` to specify a stable Puppeteer version:
          ```json
          "puppeteer": "VERSION_NUMBER"
          ```
   - **Dependencies and Side Effects**:
     - Skipping Chromium download may require manual setup of Chromium.
   - **Configuration Changes**:
     - Update environment variables and `package.json` as needed.
   - **Environment Requirements**:
     - Ensure network access to Chromium download URLs.
   - **Service Impacts**:
     - Puppeteer functionality may be delayed until Chromium is manually installed.

**Comment by AIFlowML** [comment]
Not a bug but mostly a user permission related issue.
I close this now.
